#!/usr/bin/env node
// Phase 0 helper: self-host latin woff2 for the four Engineer-Notebook faces.
// Reads Google Fonts css2, keeps only the /* latin */ block per family+weight,
// downloads the woff2 into assets/fonts/, emits css/base/fonts-local.css.
// Idempotent: safe to re-run. Static (no third-party runtime dep).

const fs = require('fs');
const path = require('path');
const https = require('https');
const { execFileSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const FONT_DIR = path.join(ROOT, 'assets', 'fonts');
const OUT_CSS = path.join(ROOT, 'css', 'base', 'fonts-local.css');

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';

// family name used in css2 -> { cssFamily, weights[] } for @font-face + filenames
const FAMILIES = [
  { css2: 'Space+Grotesk:wght@400;500;600;700', file: 'space-grotesk', weights: [400, 500, 600, 700] },
  { css2: 'IBM+Plex+Sans:wght@400;600', file: 'plex-sans', weights: [400, 600] },
  { css2: 'Architects+Daughter', file: 'architects-daughter', weights: [400] },
  { css2: 'IBM+Plex+Mono:wght@400;600', file: 'plex-mono', weights: [400, 600] },
];

function fetch(url) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers: { 'User-Agent': UA } }, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        return fetch(res.headers.location).then(resolve, reject);
      }
      if (res.statusCode !== 200) return reject(new Error(`HTTP ${res.statusCode} for ${url}`));
      const chunks = [];
      res.on('data', (c) => chunks.push(c));
      res.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')));
    }).on('error', reject);
  });
}

function download(url) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers: { 'User-Agent': UA } }, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        return download(res.headers.location).then(resolve, reject);
      }
      if (res.statusCode !== 200) return reject(new Error(`HTTP ${res.statusCode} for ${url}`));
      const chunks = [];
      res.on('data', (c) => chunks.push(c));
      res.on('end', () => resolve(Buffer.concat(chunks)));
    }).on('error', reject);
  });
}

async function main() {
  fs.mkdirSync(FONT_DIR, { recursive: true });
  const blocks = []; // accumulate @font-face latin blocks

  for (const fam of FAMILIES) {
    const cssUrl = `https://fonts.googleapis.com/css2?family=${fam.css2}&display=swap`;
    const css = await fetch(cssUrl);

    // Split into @font-face blocks
    const faceRe = /@font-face\s*{([^}]*)}/g;
    let match;
    const seen = new Set();
    while ((match = faceRe.exec(css))) {
      const body = match[1];
      const isLatin = /\/\*\s*latin\s*\*\//.test(css.slice(Math.max(0, match.index - 12), match.index));
      if (!isLatin) continue;

      const famMatch = /font-family:\s*'([^']+)'/.exec(body);
      const styleMatch = /font-style:\s*(\w+)/.exec(body);
      const weightMatch = /font-weight:\s*(\d+)/.exec(body);
      const urlMatch = /src:\s*url\(([^)]+)\)/.exec(body);
      if (!famMatch || !weightMatch || !urlMatch) continue;

      const weight = Number(weightMatch[1]);
      const style = styleMatch ? styleMatch[1] : 'normal';
      // Skip italic variable-ish duplicates we didn't ask for
      if (!fam.weights.includes(weight)) continue;
      if (style !== 'normal') continue;
      if (seen.has(`${fam.file}-${weight}`)) continue;
      seen.add(`${fam.file}-${weight}`);

      const remote = urlMatch[1].replace(/&amp;/g, '&');
      const ext = path.extname(new URL(remote).pathname) || '.woff2';
      const localName = `${fam.file}-${weight}${ext}`;
      const localPath = path.join(FONT_DIR, localName);

      const buf = await download(remote);
      fs.writeFileSync(localPath, buf);
      console.log(`downloaded ${localName} (${(buf.length / 1024).toFixed(1)} KB)`);

      blocks.push(`@font-face {
  font-family: '${fam.file}';
  font-style: normal;
  font-weight: ${weight};
  font-display: swap;
  src: url('/assets/fonts/${localName}') format('woff2');
}`);
    }
  }

  const cssOut = `/* ==========================================================================
   SELF-HOSTED FONTS — Engineer Notebook stack (latin subset only)
   Space Grotesk · IBM Plex Sans · Architects Daughter · IBM Plex Mono
   Generated by scripts/fetch-fonts.js from Google Fonts css2 (latin blocks).
   ========================================================================== */

${blocks.join('\n\n')}
`;
  fs.writeFileSync(OUT_CSS, cssOut);
  console.log(`wrote ${path.relative(ROOT, OUT_CSS)} (${blocks.length} faces)`);
}

main().catch((e) => { console.error(e); process.exit(1); });
